Feature/#21 link google analytics
YAPP-Github/22nd-iOS-Team-1-iOS pull request #22
Opened 2023-06-04 16:01 UTC by applebuddy

## ☕️ PR 요약

해당 pr에서 작업한 내역을 적어주세요.
- FirebaseAnalytics SPM 추가
- GoogleService-info.plist 추가
- GA 적용 후 로깅 시도 시 앱 크래시 문제 수정
  - tuist 설정 추가 : build setting > other linker flags > -ObjC 옵션 추가
  - GA 로그 확인을 위한 launchArguments > FIRAnalyticsDebugEnabled true 설정 추가
* TODO
  - GALogger 구현 필요
  - bundle id 고유한 identifier로 수정 필요

## 📸 ScreenShot

##### ✅ PR check list(PR 요청시 확인후 삭제해주세요)
- 앱 실행 후, 로그인 화면 좌상단 둘러보기 선택 시, GA 로그 동작 확인

```
- commit message가 적절한지 확인해주세요.
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue

close #

2023-06-04 23:13 UTC, Neph3779 requested changes
알기 어려운 오류 잡아내시느라 너무 고생 많으셨습니다!!..
API Key 관련 이슈가 있어서 코멘트 남겨놓았으니 확인 부탁드려요!

2023-06-04 23:13 UTC, Neph3779 commented on Tuist/ProjectDescriptionHelpers/Project+Templates.swift
> +    }
https://syjdev.tistory.com/27
위 블로그를 참고해보니 firebase를 dynamic 모듈이 담당하게 하면 문제를 해결할수도 있을 것 같습니다!
나중에 써드파티 관리모듈 제작시에 참고용으로 기록해놓겠습니다 🥰

2023-06-04 23:13 UTC, Neph3779 commented on Tuist/ProjectDescriptionHelpers/Project+Templates.swift
> +        ]
<img width="713" alt="image" src="https://github.com/YAPP-Github/22nd-iOS-Team-1-iOS/assets/67148595/3af1c199-b0a8-415e-9e3d-b6c6fbe79f7a">
name 자리에 debug와 relase Enum case를 넣어도 될까 걱정이 돼서 찾아봤더니
"Debug"라는 string을 반환하도록 Tuist 내부적으로 설정되어있네요~
공유차 남겨놓습니다!

2023-06-04 23:13 UTC, Neph3779 commented on Tuist/ProjectDescriptionHelpers/Project+Templates.swift
> +      ]
이 부분은 Debug모드에서만 적용되도록 하고 싶은데 
지금 당장은 어떻게 해야할지 잘 모르겠네요 🫠
Scheme, Config 파일 등 세팅 관련해 공부를 좀 더 진행한 뒤 따로 issue를 파서 리팩토링해보겠습니다!

2023-06-04 23:55 UTC, NewHooon approved these changes
와우..! 고생하셨습니다~~ GA세팅 과정 참고하도록 하겠습니다!
"other linker flags[-Objc]"가 구체적으로 어떤 역할인지 알아보도록 하겠습니다~~

2023-06-05 13:14 UTC, applebuddy commented on Projects/Cafe/Resources/GoogleService-Info.plist
파일 추가한 수정사항은 제거했습니다.
다만, git ignore를 하기 전에, tuist 설정으로 GoogleService-info.plist를 추가하는 설정은 해본적이 없어서 확인 좀 해봐야 할것 같아요~

2023-06-05 13:15 UTC, applebuddy commented on Tuist/ProjectDescriptionHelpers/Project+Templates.swift
> +        ]
넵 저도 하드코딩으로 해야하나했다가 발견해서 적용해봤습니다~

2023-06-05 13:15 UTC, applebuddy commented on Tuist/ProjectDescriptionHelpers/Project+Templates.swift
> +      ]
기대하겠습니다. 👍

2023-06-05 13:26 UTC, Neph3779 approved these changes
고생 많으셨습니다!!

2023-06-05 15:15 UTC, merged