Feature/#15 cafe map view
YAPP-Github/22nd-iOS-Team-1-iOS pull request #24
Opened 2023-06-07 04:50 UTC by NewHooon

## ☕️ PR 요약

해당 pr에서 작업한 내역을 적어주세요.
- 네이버 맵 적용한 CafeMapVIew 구현
- 커스텀 Pin 구현
- 위도, 경도 받아와 지도에 표시
- viewStore 추가

## 📸 ScreenShot

PR과 관련된 화면을 첨부해주세요.
<div>
<img src="https://github.com/YAPP-Github/22nd-iOS-Team-1-iOS/assets/108966759/fcef7096-5d42-4551-87c7-ae567c0a9c39" width="200">
<img src="https://github.com/YAPP-Github/22nd-iOS-Team-1-iOS/assets/108966759/ee8a252d-25cc-47da-88b5-abc6cb09aa90" width="200">
</div>

##### ✅ PR check list(PR 요청시 확인후 삭제해주세요)

```
- commit message가 적절한지 확인해주세요.
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue

close #15

2023-06-07 06:06 UTC, Neph3779 requested changes
고생 많으셨습니다!
남겨놓은 코멘트 확인 부탁드려요!
코멘트로 남기진 못했지만
보통 프로퍼티, init, 메서드들 사이에 한줄씩 띄워서 너무 다닥다닥 붙어있지 않도록
한줄씩 띄워주어 조절해주는 경우가 많았었는데 이 부분은 다음 팀 회의때 룰을 정해봐도 좋을 것 같습니다~

2023-06-07 06:06 UTC, Neph3779 commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +  }
makeUIView라는 네이밍은 UIView를 반환할 것 같은 이름이네요!.. (NMFNaverMapView가 UIView의 서브클래스이긴 하지만요)
makeNaverMapView와 같이 조금 더 의미가 들어간 네이밍이면 좋겠어요!

2023-06-07 06:06 UTC, Neph3779 commented on Projects/Cafe/Sources/View/MarkerView.swift
> +  var description: String = ""
디폴트 값으로 설정해둔 부분이라 생각합니다~
enum과 type 프로퍼티를 활용해 상수를 한곳에 보관할 수 있으면 더 좋을 것 같아요!

```swift
enum DefaultText {
  static let cafeName = "학림 다방"
  static let subTitle: String = "서울특별시 종로구 대학로 119"
  static let description: String = ""  
```

2023-06-07 06:06 UTC, Neph3779 requested changes
고생 많으셨습니다!
남겨놓은 코멘트 확인 부탁드려요!
코멘트로 남기진 못했지만
보통 프로퍼티, init, 메서드들 사이에 한줄씩 띄워서 너무 다닥다닥 붙어있지 않도록
한줄씩 띄워주어 조절해주는 경우가 많았었는데 이 부분은 다음 팀 회의때 룰을 정해봐도 좋을 것 같습니다~

2023-06-07 06:17 UTC, NewHooon commented on Projects/Cafe/Sources/CafeApp.swift
> +//      )
네 맞습니다~ MapView에 대한 Tab이 정해지지 않아, 위와 같이 기술했었습니다~!
주석된 부분은 우선 제거하도록하겠습니다~

2023-06-07 06:19 UTC, NewHooon commented on Projects/Cafe/Sources/View/CafeMapView.swift
> +// }
네 맞습니다.. NaverMapView를 PreView로 띄우다보니 UI 수정 시, Crash Error가 자꾸 Xcode에 나오더라구요.
API호출이 지속적으로 발생해서 생긴 문제인 것 같았습니다~ 그럼 해당 부분 주석을 우선 삭제하도록 하겠습니다.

2023-06-07 06:20 UTC, NewHooon commented on Projects/Cafe/Project.swift
> +    "NMFClientId": ""
좋습니다~~ 참조용으로 올려주신 페이지 보면서 key값 설정하겠습니다!

2023-06-07 06:21 UTC, NewHooon commented on Projects/Cafe/Sources/CafeMapCore.swift
> +    var region: CLLocationCoordinate2D = CLLocationCoordinate2D(latitude: 1, longitude: 1)
초기에 로직 구성시, CurrentLocation 대체용으로  디폴트값을 두었습니다. 
실제 앱에서 위치 권한이 없을 때, 디폴트로 설정될 위치가 필요한 경우 어디로 설정하면 좋을지 같이 논의해보면 좋을 것 같습니다.

2023-06-07 06:23 UTC, NewHooon commented on Projects/Cafe/Sources/CafeMapCore.swift
> +          print("Error")
네 좋습니다~! 꼼꼼하게 리뷰해주셔서 감사합니다. 미처 생각하지 못했는데 수정해보도록 하겠습니다!

2023-06-07 06:25 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +  private var isAuthorizationReturned: CheckedContinuation<CLAuthorizationStatus, Never>?
CLLocationManager에서 CLLocationManagerDelegate 패턴을 준수하며 이에 따라 동작하는데, 
가령 현재위치 조회를 위해 locationManager.requestLocation() -> Delegate "func updateLocation.." -> 반환 
플로우 이기 때문에, 변수로 설정하여 Delegate에서 location반환이 끝났을 경우, resume을 반환하는 구조이기에 위와 같이 사용하였습니다.

2023-06-07 06:27 UTC, NewHooon commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +    let lng = coordinate.longitude
좋습니다~~ "latitude, longitude"의 방식으로 수정하겠습니다.

2023-06-07 06:27 UTC, NewHooon commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +  }
"func makeUIView" 메서드의 경우, UIViewRepresentable의 프로토콜 준수할 경우, 반드시 설정해줘야하는 메서드이기에 함수명 변경이 어려울 것 같습니다

2023-06-07 06:28 UTC, NewHooon commented on Projects/Cafe/Sources/View/MarkerView.swift
> +  var description: String = ""
네 맞습니다~! 좋은 방법인 것 같습니다!! 알려주신 방법으로 수정해보겠습니다~

2023-06-07 06:40 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +      }
```swift 
func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
    region = locations.first?.coordinate ??  CLLocationCoordinate2D(latitude: 37.5819, longitude: 127.0017)
    isLocationReturend?.resume(returning: region)
    isLocationReturend = nil
  }

func locationManager(_ manager: CLLocationManager, didFailWithError error: Error) {
    isLocationReturend?.resume(throwing: error)
...
  }
  ``` 
위의 코드에서, locationManager.requestLocation() 요청 시에 위치 조회 성공 시,  "didUpdateLocations locations" 작동하며
만약 위치 조회가 실패할 경우 delegate에서 "didFailWithError" 메서드가 실행되는데 그 과정에서 발생하는 error를 throwing 하는과정입니다. 현재위치 조회시, CoreLocation에서 위치를 업데이트 하는 정확한 시점을 특정 지을 수 없어서 비동기 방식으로 사용하게 되었습니다.

2023-06-07 06:48 UTC, NewHooon commented on Projects/Cafe/Sources/CafeMapCore.swift
> +    case let .currentLocationResponse(currentLocation):
맞습니다..!  TCA Tutorial에서는 case let 방식을 사용하고 있어서 일단 위와 같이 작성하였습니다~
같이 의논해서 규칙을 정하면 좋을 것 같습니다.

2023-06-07 06:51 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +  private var authorization: CLAuthorizationStatus
region의 경우, 실제 유저가 이동하는 상황에서 위치 정보 조회 시, 지속적으로 변경될 수 있기에 Var로 선언하였습니다.
authorization의 경우에는 let으로 사용해도 될 것 같습니다~

2023-06-07 06:56 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +  private var authorization: CLAuthorizationStatus
넵 좋습니다~

2023-06-07 07:15 UTC, Neph3779 commented on Projects/Cafe/Sources/LocationManager.swift
> +  private var authorization: CLAuthorizationStatus
CLLocationCoordinate2D가 struct였군요~
class 타입일거라 생각해서 남긴 질문이었습니다!

2023-06-07 07:31 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +      }
네 맞습니다~ 제가 실수로 위에다 CLLocationManagerDelegate를 작성하고, 아래에 Extension LocationManager 라고 
작성했네요.. 죄송합니다.🥲 수정하겠습니다..!

2023-06-07 14:12 UTC, applebuddy commented on Projects/Cafe/Sources/CafeApp.swift
> +import ComposableArchitecture
P3: 다음에 제안하고 싶은 컨벤션인데, import 할 module은 사전순으로 명시하면 좋을 것 같다는 생각이에요. 다음에 추가로 얘기해봐요~

2023-06-07 14:34 UTC, applebuddy requested changes
컨벤션 관련 내용이 주 인것 같은데, 나중에 컨벤션 관련 얘기 많이 나누어보며 룰 정해보면 좋을 것 같습니다.
리뷰 확인 부탁드립니다. 👍

2023-06-07 14:34 UTC, applebuddy commented on Projects/Cafe/Sources/CafeApp.swift
> +//      )
P2: 주석이 꼭 필요하다면, 주석처리를 한 이유 등을 같이 남기면 좋을 것 같아요. (TODO, FIXME 주석 등...)

2023-06-07 14:34 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +  enum Action: Equatable {
P2: 여기도 한줄 공백 두면 좋을 것 같아요.

2023-06-07 14:34 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +struct CafeMapCore: ReducerProtocol {
P2: 한줄 공백 두면 좋을 것 같아요.

2023-06-07 14:34 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +          print("Error")
P2: debugPrint를 대신 쓰면 어떨까요. 어떤 에러인지도 상세를 좀더 붙히면 좋을 것 같습니다.

2023-06-07 14:34 UTC, applebuddy commented on Projects/Cafe/Sources/LocationManager.swift
> +  func fetchCurrentLocation() async throws -> CLLocationCoordinate2D {
P2: 메서드 사이 공백 한줄 씩 넣으면 좋을것 같습니다.

2023-06-07 14:34 UTC, applebuddy commented on Projects/Cafe/Sources/LocationManager.swift
> +class LocationManager: NSObject, DependencyKey, CLLocationManagerDelegate {
P3: final 키워드를 붙여도 될 것 같습니다.

2023-06-07 14:45 UTC, applebuddy commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +extension NaverMapView {
중요한 부분 같아 보이는데 TODOs: 로 쓰니까 경고로 잡히질 않네요.. 이런 경우 TODO 주석을 어떻게 쓰면 좋을까 싶네요

2023-06-07 15:08 UTC, NewHooon commented on Projects/Cafe/Sources/CafeApp.swift
> +import ComposableArchitecture
P3: 오~ 사전순으로 import 명시하는 것도 좋은 것 같습니다!
P2: 확인하고 반영하겠습니다~~

2023-06-07 15:11 UTC, NewHooon commented on Projects/Cafe/Sources/CafeMapCore.swift
> +          print("Error")
맞습니다! 임시적으로 Print("Error")라고 적어놓았던 부분이라, 말씀해주신 debugPrint로 수정하겠습니다~!

2023-06-07 15:12 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +class LocationManager: NSObject, DependencyKey, CLLocationManagerDelegate {
좋은 리뷰감사합니다! final 키워드로 class 최적화 할 수 있도록 키워드 추가하겠습니다!

2023-06-07 15:13 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +extension LocationManager {
확인했습니다!

2023-06-07 15:15 UTC, NewHooon commented on Projects/Cafe/Sources/View/CafeMapView.swift
> +  var body: some View {
넵 이번주 일요일 코드 컨벤션 관련해서 같이 논의해보면 좋을 것 같습니다~!

2023-06-07 15:16 UTC, NewHooon commented on Projects/Cafe/Sources/View/MarkerView.swift
> +struct AddressBubble: View {
특별한 이유는 없습니다~! 참고한 레퍼런스에서 명칭을 똑같이 따왔던 것 같네요😅 
반영하겠습니다~

2023-06-07 15:17 UTC, NewHooon commented on Projects/Cafe/Sources/View/MarkerView.swift
> +            VStack(spacing: 0) {
넵 확인하고 반영하겠습니다!

2023-06-07 15:17 UTC, NewHooon commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +    moveCamreaToPoistion(viewStore.region, uiView)
엇 오타가 있었네요..수정하겠습니다!

2023-06-09 08:45 UTC, NewHooon reviewed
모든 내용 반영 완료했습니다~

2023-06-10 08:28 UTC, applebuddy reviewed
추가로 의견 남겨봐요 컨벤션은 내일 또 얘기 해보면 좋겠습니다.

2023-06-10 08:28 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +}
위도, 경도를 전부 비교하도록 조건 추가해주세요~

2023-06-10 08:28 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +    case .requestAuthorization:
Action enum 케이스 마다 공백을 둘지 안둘지? 회의때 정해도 좋을 것 같아요. (notion에 적음)

2023-06-10 08:28 UTC, applebuddy commented on Projects/Cafe/Sources/LocationManager.swift
> +import ComposableArchitecture
사전순 나열하기로 정해지면 이런것도 맞추면 좋겠습니다.

2023-06-10 08:28 UTC, applebuddy commented on Projects/Cafe/Sources/LocationManager.swift
> +  private var isLocationReturend: CheckedContinuation<CLLocationCoordinate2D, Error>?
@Neph3779 위 제안이 어떤 의도로 적은건지 궁금합니다~ (전, 후가 같아보여서..)

2023-06-10 08:28 UTC, applebuddy commented on Projects/Cafe/Sources/LocationManager.swift
> +      return try await withCheckedThrowingContinuation { [weak self] continuation in
try await 만 써도 되는 케이스인데 이런경우 return 을 붙힐지 말지도 정해보면 좋을 것 같아요.

2023-06-10 08:28 UTC, applebuddy commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +  let view = NMFNaverMapView()
아래 처럼 줄일 수 도 있을 것 같아요~
```swift
@ObservedObject var viewStore: ViewStoreOf<CafeMapCore>
```

2023-06-10 08:28 UTC, applebuddy commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +  let view = NMFNaverMapView()
개취인데... view보다는 mapView 정도로 바꾸는건 어떨까 생각 들었습니다.

2023-06-10 08:28 UTC, applebuddy commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +  func mapSetting(_ view: NMFNaverMapView) {
메서드 명이 보통은 동사가 앞에 오는 편 같아서 남깁니다.

2023-06-10 11:44 UTC, applebuddy reviewed
네이버지도 처음 사용해봤을텐데 고생 많으셨어요.
리뷰 추가로 남깁니다~

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +    var region: CLLocationCoordinate2D = CLLocationCoordinate2D(latitude: 1, longitude: 1)
나중에 우리 주 타겟 지역 좌표를 넣어두어서 default 좌표로 사용하면 좋을 것 같습니다.

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +    case currentLocationResponse(CLLocationCoordinate2D)
TaskResult를 사용해서 currentLocationResponse에서 응답 결과를 처리하면 좋을 것 같습니다.

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +      }
.run { ... } catch: { error, send in ... }  처럼 .run 에서 기본적으로 catch 블럭을 제공하는데 이 catch 블럭을 사용하는것도 좋을 것 같아요.

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +      }
여기는 실제 버튼이 탭 되는 경우가 아닌데, currentLocationButtonTapped 를 실행하고 있어서 조금 Action 역할에 혼동이 생길것 같다는 생각이 들었어요.
currentLocationButtonTapped 에서 실행되는 currentLocation 요청 로직을 별도 Action case로 분리하고 그걸 51번 라인에서 실행하는게 어떨까요

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/LocationManager.swift
> +//  Cllocai.swift
주석명과 파일명을 맞춰주면 좋을 것 같아요.

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/View/CafeMapView.swift
> +          .ignoresSafeArea()
나중에 NaverMapView에 대한 Reducer를 분리하게 되면 생성자를 store로 받도록 하고, 내부에서 ViewStore를 생성하는 방식으로 바꾸어서 개선할 수 있을 것 같아요. 
```swift
// 나중에 Reducer 분리가 된다면...
NaverMapView(store: store.scope(...))
```

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/View/CafeMapView.swift
> +  @State var heartButtonTapped: Bool = false
나중에 UI가 구체화 된다면 Reducer > State의 BindingState나 viewStore.binding(...) 개념으로 방식을 바꾸면 좋을 것 같습니다.

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +struct CafeMapCore: ReducerProtocol {
Feature 단위 Reducer의 이름 끝에 무언가 붙히는게 좋다는 생각은 드는데 이부분도 iOS 회의때 얘기해보면 좋겠습니다.
ex) TCA 샘플 코드를 보면 ReducerProtocol을 채택하는 구조체 명을 Counter, CounterFeature 등으로 혼재해서 사용 중
ex) 현업에서는 초기에 끝에 Core를 붙히는 방식으로 했다가 ReducerProtocol 방식으로 변경 후에는 Core를 떼기도 했음. (전, 후 모두 파일명은 그대로 Core를 붙힘..)
이부분 룰을 정해보면 좋겠습니다.

2023-06-10 11:44 UTC, applebuddy commented on Projects/Cafe/Sources/CafeMapCore.swift
> +      }
```swift
    case .currentLocationButtonTapped:
      // TODO: Logger제작 시, Logging 예정.
      return .run { send in
        let region = try await locationManager.fetchCurrentLocation()
        await send(.currentLocationResponse(region))
      } catch: { error, send in
        debugPrint(error)
      }
```

2023-06-10 13:47 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +//  Cllocai.swift
파일주석이 변경되있었네요..?! 수정하겠습니다~

2023-06-10 14:16 UTC, NewHooon commented on Projects/Cafe/Sources/CafeMapCore.swift
> +}
수정했습니다~

2023-06-10 14:17 UTC, NewHooon commented on Projects/Cafe/Sources/LocationManager.swift
> +      return try await withCheckedThrowingContinuation { [weak self] continuation in
좋습니다~~

2023-06-10 14:24 UTC, NewHooon commented on Projects/Cafe/Sources/CafeMapCore.swift
> +      }
좋은 피드백 감사합니다~ 아직 TCA에 대한 학습이 더 필요한 것 같습니다..! Error 처리 방법 적용해보겠습니다.

2023-06-10 14:26 UTC, NewHooon commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +  func mapSetting(_ view: NMFNaverMapView) {
반영해서 setupMap으로 수정하겠습니다~!

2023-06-10 14:26 UTC, NewHooon commented on Projects/Cafe/Sources/CafeMapCore.swift
> +    case currentLocationResponse(CLLocationCoordinate2D)
피드백 주신 부분 학습해서 코드에 반영하도록 하겠습니다~!

2023-06-10 14:28 UTC, NewHooon commented on Projects/Cafe/Sources/CafeMapCore.swift
> +      }
네 저도 코드 살펴보니, 해당 부분에서 어색함을 느꼈습니다! fetchCurrentLocation으로 별도 Action을 추가하고자 합니다~

2023-06-10 14:35 UTC, NewHooon commented on Projects/Cafe/Sources/View/NaverMapView.swift
> +  let view = NMFNaverMapView()
```swift
func mapSetting(_ view: NMFNaverMapView) {
    view.mapView.locationOverlay.hidden = false
    view.mapView.maxZoomLevel = 50
    view.mapView.minZoomLevel = 0
    ...
  }
```
저도 기존에 mapView로 설정했었지만, 위 코드에서 표기된 것 처럼 NMFNaverMapView의 프로퍼티로 mapView가 이미 존재해서
mapView.mapView 꼴로 혼동을 불러일으켜 view로 설정했었습니다.🥲

2023-06-11 11:27 UTC, Neph3779 approved these changes
빌드, 실행 잘 되는 것 확인하였습니다~
approve 해놓을게요!

2023-06-11 11:31 UTC, applebuddy approved these changes

2023-06-11 11:32 UTC, applebuddy commented
고생 많으셨습니다~! 👍🏽👍🏽

2023-06-11 11:35 UTC, merged