Feature/#29 CoreNetwork 계층 제작
YAPP-Github/22nd-iOS-Team-1-iOS pull request #30
Opened 2023-06-16 06:37 UTC by Neph3779

## ☕️ PR 요약
- CoreNetwork type을 제작했습니다.
- 이전 프로젝트 진행때 서버로 의문의 공격이 들어온적이 있어서 base url은 git ignore에 넣어 관리하도록 했습니다.
  - 해당파일은 dm으로 보내드리겠습니다.
- API 통신의 견본이 될 HealthCheckClient를 제작했습니다.
  - 이 외의 API Call의 경우 아직 403 에러가 내려오고 있기에 사용 가능한 call부터 제작했습니다.
  - 필요한 api call은 별도의 이슈를 파서 작업할 예정입니다.

## Lint 규칙 추가
```
line_length:
 ignores_function_declarations: true
 ignores_comments: true
```
함수 선언부는 길어져도 line_length에서 경고하지 않도록 수정했습니다.
주석의 길이는 길어져도 line_length에서 경고하지 않도록 수정했습니다.

수정한 규칙에 대한 의견공유 부탁드려요!

#### Linked Issue

close #29

2023-06-16 07:07 UTC, applebuddy reviewed
몇개 의견 남겼습니다. 확인 부탁드립니다~

2023-06-16 07:07 UTC, applebuddy commented on Projects/Network/Sources/KeyChainManager.swift
> +  func updateItem(key: Any, value: Any) -> Bool
Q. 여기는 Any 타입으로 사용할 수밖에 없는 것 맞죠?

2023-06-16 07:07 UTC, applebuddy commented on Projects/Network/Sources/KeyChainManager.swift
> +    print("getItem Error : \(key)")
여기도 debugPrint 가 좋지 않을까 생각해요 print를 사용한 이유가 있으면 공유 부탁드려요~

2023-06-16 07:07 UTC, applebuddy commented on Projects/Network/Sources/KeyChainManager.swift
> +                                kSecAttrAccount: key]
여기 딕셔너리 개행이 좀 이상한 것 같아서 확인 부탁드려요

2023-06-16 07:07 UTC, applebuddy commented on Projects/Network/Sources/KeyChainManager.swift
> +                                            kSecAttrAccount: "lookAroundToken"]
여기도 개행 상태 확인 부탁드립니다.

2023-06-16 07:12 UTC, Neph3779 commented on Projects/Cafe/Sources/App/Dependencies/HealthCheckClient.swift
> +import Network
사전순을 깜빡했네요! 수정했습니다~

2023-06-16 07:13 UTC, Neph3779 commented on Projects/Network/Sources/CoreNetwork.swift
> +      print("There is no jwt token")
여기는 전부 logger 사용으로 바뀔 것 같지만
그래도 debugPrint로 바꿔놓도록 하겠습니다!

2023-06-16 07:15 UTC, Neph3779 commented on Projects/Network/Sources/CoreNetwork.swift
> +      guard let exception = try? JSONDecoder().decode(NetworkException.self, from: data) else {
그렇게되면 do catch문이 반복되어서 보기 불편할거라 생각했습니다.
옵셔널 바인딩과정에서 throw 구문이 실행되기에 로직은 똑같아서 괜찮다 생각했는데
그래도 do catch를 사용하는게 적절할까요? 의견 주시면 감사하겠습니다!

2023-06-16 07:18 UTC, Neph3779 commented on Projects/Network/Sources/KeyChainManager.swift
> +  func updateItem(key: Any, value: Any) -> Bool
예전 코드여서 다시 읽어보니
String으로 모두 교체해도 전혀 무방하네요
String으로 두고 쓰다 추후에 Any나 다른 타입이 필요하면 추가하겠습니다!

2023-06-16 07:18 UTC, Neph3779 commented on Projects/Network/Sources/KeyChainManager.swift
> +    print("getItem Error : \(key)")
여기도 logger로 교체될 예정이라 print를 넣어놓았는데
debugPrint로 교체하겠습니다~!

2023-06-16 07:21 UTC, NewHooon reviewed
수고하셨습니다~ 개인적으로 궁금한 부분 의견 남겼습니다.

2023-06-16 07:21 UTC, NewHooon commented on Projects/Network/Sources/CoreNetwork.swift
> +    return try await withCheckedThrowingContinuation({ continuation in
이 부분의 경우 URLSession에서 제공하는 async 메서드를 사용해서 해결할 수 있을 것 같은데,
"withCheckedThrowingContinuation"을 사용한 이유가 무엇일까요~?? 
Response만 필요한 경우, 아래의 방식으로 사용할 수 있을 것 같은데 궁금해서 질문 남겨봅니다~!
```swift
let (_ , response) = try await URLSession.shared.data(for: request)
```

2023-06-16 07:24 UTC, Neph3779 commented on Projects/Network/Sources/CoreNetwork.swift
> +    return try await withCheckedThrowingContinuation({ continuation in
async await 코드 부분은 최신 커밋에서는 수정되어있는데 확인해주시겠어요?
response 부분은 반영하겠습니다!

2023-06-16 07:26 UTC, NewHooon commented on Projects/Network/Sources/CoreNetwork.swift
> +    return try await withCheckedThrowingContinuation({ continuation in
확인했습니다~!

2023-06-16 07:27 UTC, NewHooon submitted a review, later dismissed

2023-06-16 20:14 UTC, applebuddy requested changes
추가로 의견 남겨놓았습니다. 확인 부탁드려요. 🙏🏻 (빌드 잘 되었어요.)

2023-06-16 20:14 UTC, applebuddy commented on Projects/Network/Sources/CoreNetwork.swift
> +    if let token = KeychainManager.shared.getItem(key: "token") as? String {
여기 String 타입캐스팅을 할 필요가 없다고 나오네요. 확인 부탁드려요~

2023-06-16 20:14 UTC, applebuddy commented on Projects/Network/Sources/CoreNetwork.swift
> +    } else if let lookAroundToken = KeychainManager.shared.getItem(key: "lookAroundToken") as? String {
여기도 as? String 이 꼭 필요한지 확인 부탁드립니다.

2023-06-16 20:14 UTC, applebuddy commented on Projects/Network/Sources/Extensions/URLComponentsExtension.swift
> +    guard let url = url else { return nil }
아래처럼 줄이면 좋겠네요.
```swift
guard let url else { return nil }
```

2023-06-16 20:14 UTC, applebuddy commented on Projects/Network/Sources/Extensions/URLComponentsExtension.swift
> +    if let httpBody = httpBody {
여기도 if let httpBody { ... } 로 줄이면 좋겠어요.

2023-06-16 20:14 UTC, applebuddy commented on Projects/Network/Sources/Extensions/URLComponentsExtension.swift
> +    guard let url = url else { return nil }
그리고 메서드 길이 제한 룰을 예외로 둔 것 같은데, 아래처럼 개행을 하면 왠만한건 라인 룰에 위배되지 않아서 길이룰 제한은 유지해도 될 것 같다고 생각했는데, 어떤 케이스 때문에 lint 룰에 예외를 두었는지 좀 더 자세히 듣고 싶어요~

```swift
func toURLRequest(
    method: HTTPMethod,
    httpBody: Data? = nil,
    contentType: String = "application/json"
  ) -> URLRequest? { ... }
```

2023-06-17 03:50 UTC, Neph3779 commented on Projects/Network/Sources/CoreNetwork.swift
> +    if let token = KeychainManager.shared.getItem(key: "token") as? String {
확인했습니다! 수정할게요~!

2023-06-17 03:52 UTC, Neph3779 commented on Projects/Network/Sources/CoreNetwork.swift
> +    } else if let lookAroundToken = KeychainManager.shared.getItem(key: "lookAroundToken") as? String {
이 부분도 수정했습니다!

2023-06-17 03:54 UTC, Neph3779 commented on Projects/Network/Sources/Extensions/URLComponentsExtension.swift
> +    guard let url = url else { return nil }
메서드를 인자별로 줄바꿈을 해서 받는 경우도 많지만
파일이 길어짐에 따라 가독성 측면에서 안좋다고 느껴지는 경우가 종종 있었기에
메서드 선언부 정도는 lint에서 검사하지 않는게 어떨까 싶었습니다!
generic 인자가 더 많이 쓰이게되면 애매모호해지는 줄바꿈 기준도 정해야하는 오버헤드가 있다고 느꼈거든요 ㅎㅎ

물론 제 의견일 뿐이고 팀 내에서 기준을 다시 정해보면 좋겠습니다!

2023-06-17 03:55 UTC, Neph3779 commented on Projects/Network/Sources/Extensions/URLComponentsExtension.swift
> +    if let httpBody = httpBody {
우선 이 부분에서 변수를 shadowing 하도록 한 이유를 설명드리면
Swift 버전이 낮은 개발환경에서 개발하는 팀원이 위의 코드를 컴파일할 수 없기 때문이었습니다~
저희 팀은 모두 최신버전으로 업데이트를 했기에 해당사항이 없으니 수정하겠습니다!

2023-06-17 04:03 UTC, NewHooon approved these changes

2023-06-17 05:35 UTC, applebuddy approved these changes
고생 많으셨습니다 👍🏽👍🏽

2023-06-17 05:51 UTC, merged