[Feat] #50 플로팅 버튼 api 연동 및 로직 구현
YAPP-Github/22nd-iOS-Team-1-iOS pull request #57
Opened 2023-06-25 05:42 UTC by NewHooon

## ☕️ PR 요약

플로팅 버튼 api 연동 및 로직 구현 작업을 진행하였습니다.
- refreshButton 클릭 시, API 호출 및 마커 표시

## 📸 ScreenShot
<image src = "https://github.com/YAPP-Github/22nd-iOS-Team-1-iOS/assets/108966759/3462348b-4b69-4fad-86c1-80e1fab5d68b" width = "200" >

## ❌ 문제상황
- 마커 불러오기[ addMarker] 실행 시, 메모리 기존 마커들이 남아있는 문제
<img width="1116" alt="image" src="https://github.com/YAPP-Github/22nd-iOS-Team-1-iOS/assets/108966759/8927ac21-6072-47f4-9094-9837d912d80d">

#### Linked Issue

close #50

2023-06-25 06:36 UTC, Neph3779 requested changes
고생하셨습니다~
lint 규칙들을 조금만 더 천천히 점검해주시면 더 좋을 것 같아요!
<img width="1520" alt="image" src="https://github.com/YAPP-Github/22nd-iOS-Team-1-iOS/assets/67148595/b7212403-118a-4a13-988a-0886bf9ad371">

메모리 누수 문제는 아직 원인지점 파악을 못했습니다~
먼저 남겨드린 코멘트부터 참고 부탁드려요!

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case markerListClear
action의 네이밍이 어색한 것 같아요!
marker list clear는 무엇을 뜻하는건가요?..
마커 리스트를 모두 지우는 동작이면 clearMarkerList가 맞을 것 같습니다!

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var refreshComplete: Bool = false
isRefreshCompleted 등의 Bool값에 알맞은 변수명이 필요해보여요

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var nowCameraPosition: CLLocationCoordinate2D?
now라는 prefix가 적절한지 잘 모르겠습니다!
current가 더 어울릴 것 같아요

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
>      case requestAuthorization
요 부분도 어떤 권한을 요청하는건지 더 구체적으로 나와있으면 좋겠습니다!

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
>      case searchTextFieldTyped(text: String)
검색어의 변화를 감지하는 것이니 searchTextDidChanged가 더 좋을 것 같아요~

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case cameraPositionUpdate(CLLocationCoordinate2D)
요것두 update를 진행하는거라면 update가 앞으로 가는게 좋아보이고
update된것을 감지하는거라면 updated와 같이 쓰는게 좋아보여요

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case refreshCompleteToFalse
코드에서 @@@To$$$ 와 같은 네이밍이 종종 보이고 있는데
조금 헷갈리는 것 같습니다~
더 명확한 네이밍이면 좋겠습니다

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var cafeList:[CafeMarkerData] = []
: 뒤에 공백 필요해요!

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/MarkerView.swift
> +
요건 Entity인가요? Entity 폴더에 들어가면 좋을 것 같아요
isSelected는 어디에 쓰이는지도 알려주시면 감사하겠습니다~

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/MarkerView.swift
> +        .padding(.bottom, 3)
여긴 왜 indent가 달라졌나요?..

2023-06-25 06:36 UTC, Neph3779 commented on Tuist/signing /coffice.Release.mobileprovision
이 파일은 왜 바뀐건가요? 경로도 잘못되어 보여요

2023-06-25 06:36 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +      dataSource.title = "정보 창 내용"
dataSource 설정 부분 불필요한 내용은 지워주세요~
(NMFINfoWindowDefaultTextSource는 사용하지 않고 있네요)

2023-06-25 06:50 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case markerListClear
오호 그러네요~ 지금보니 네이밍이 어색하네요! 반영하겠습니다

2023-06-25 06:50 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var refreshComplete: Bool = false
넵 이부분도 반영하겠습니다~

2023-06-25 06:52 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
>      case requestAuthorization
위치권한 습득 부분입니다~  location이 생략되어 혼동이 올 것 같네요~! 수정하겠습니다.
ex) requestAuthorization =>  requestLocationAuthorization

2023-06-25 06:54 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
>      case searchTextFieldTyped(text: String)
해당 코드는 경태님이 이전에 작성하셨던 코드인 것 같습니다~
@applebuddy  한번 보시고 의견주시면 제가 수정해서 올리겠습니다

2023-06-25 06:54 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var cafeList:[CafeMarkerData] = []
확인했습니다!

2023-06-25 06:56 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/MarkerView.swift
> +
선택된 카페 마커를 분기처리하기위해, isSelected를 넣어 선택된 마커의 이벤트 처리를 위해 작성해 놓았습니다.
infoWindow를 사용한다면, 수정해도 될 것 같습니다

2023-06-25 06:57 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +      dataSource.title = "정보 창 내용"
네~ 반영하겠습니다

2023-06-25 06:58 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/MarkerView.swift
> +        .padding(.bottom, 3)
엇.. 한번 확인 해보겠습니다

2023-06-25 06:59 UTC, NewHooon commented
>

2023-06-25 07:04 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var nowCameraPosition: CLLocationCoordinate2D?
current가 조금 더 나아보이네요~ current로 수정하겠습니다

2023-06-25 07:14 UTC, NewHooon commented on Tuist/signing /coffice.Release.mobileprovision
기존 local 폴더 삭제 후, 다시 만드는 과정에서 Signing 파일을 추가하는 부분에서 잘못된 것 같습니다~  
확인했습니다!

2023-06-25 07:21 UTC, NewHooon commented
@Neph3779  
코멘트에 남겨주신 부분과 유사한데 메소드 구분 또는 TCA구조에서 switch case가 붙어있어 가독성이 떨어져서 분리하였는데,
붙이는 방식으로 진행할까요~?
<img width="1445" alt="image" src="https://github.com/YAPP-Github/22nd-iOS-Team-1-iOS/assets/108966759/9ade6269-6960-47c6-885c-71521be0e388">

2023-06-25 07:36 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
>      case searchTextFieldTyped(text: String)
저도 동의합니다~ 수정하면 좋을것같아요

2023-06-25 08:00 UTC, applebuddy requested changes
코멘트 확인 부탁드려요~ 수정되면 좋겠다고 생각한 내용은 P1으로 적어두었습니다.

2023-06-25 08:17 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +import NMapsMap
확인했습니다~~

2023-06-25 08:17 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var cafeList:[CafeMarkerData] = []
확인했습니다~~!

2023-06-25 08:19 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case refreshCompleteToFalse
이 부분은 저도 고민이 되네요.. 명확한 네이밍이 없을까 싶네요

2023-06-25 08:19 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case cameraPositionUpdate(CLLocationCoordinate2D)
넵~~

2023-06-25 08:22 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +        return .none
적용했습니다~~!

2023-06-25 08:23 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +
넵~~

2023-06-25 08:23 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CustomInfoWindowView.swift
> +class CustomInfoWindowView: UIView {
반영했습니다~

2023-06-25 08:25 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/MarkerView.swift
> +//
넵 확인했습니다

2023-06-25 08:25 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +
개행할 때, 공백이 들어가네요.. 확인했습니다

2023-06-25 08:26 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +
맞아요 그래서 디스코드에 남긴 설정 하면 편합니다~

2023-06-25 08:28 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +          print("infoWindow Close")
오류 및 버그 출력 보다는 단순 gesture 확인용으로 사용된 것 같습니다.
debugPrint로 변경하겠습니다.

2023-06-25 08:40 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
>      case searchTextFieldTyped(text: String)
searchTextDidChanged로 수정하겠습니다~~

2023-06-25 08:53 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +import ComposableArchitecture
사전순으로 하면 ComposableArchitecture이 CoreLocation보다 먼저 나와야 해서 한번 더 확인 부탁드립니다.

2023-06-25 08:57 UTC, Neph3779 commented
<img width="940" alt="image" src="https://github.com/YAPP-Github/22nd-iOS-Team-1-iOS/assets/67148595/9f71dc54-84bb-4172-8a56-6d7fdb9956a2">
요건 한 줄을 띄워서 나는 워닝이 아니라
줄을 띄웠는데 indent만큼 왼쪽 공백이 생겨서 나는 워닝입니다~

2023-06-25 09:06 UTC, NewHooon commented
>  요건 한 줄을 띄워서 나는 워닝이 아니라 줄을 띄웠는데 indent만큼 왼쪽 공백이 생겨서 나는 워닝입니다~

아하 그렇군요..! 그럼 switch문에서 모든 case 및 action의 경우, 공백 추가 없이 붙일까요~?

2023-06-25 09:42 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case refreshCompleteToFalse
ex) iscurrentButtonTapped를 누르면 True 상태가 되는데, 이 값을 다시 false로 바꿔주는 액션으로
@@@toFalse 이런방식으로 정의했었습니다~~

2023-06-25 10:52 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case refreshCompleteToFalse
@Neph3779  다음과 같이 네이밍 변경하고자 합니다~ 어떠신가요?
ex) refreshCompleteToFalse  -> isRefreshCompletedFalse
ex) currentButtonToFalse -> isCurrentButtonTappedFalse

2023-06-25 10:54 UTC, applebuddy approved these changes
수고 많으셨습니다.  👍

2023-06-25 11:42 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +      DispatchQueue.main.async { viewStore.send(.offCurrentButtonTapped) }
메인큐 설정을 action case에서 실행하도록 하면 문제가 있나요?
action 내에서 실행하면 여기 메인큐 중복코드를 없앨 수 있을 것 같아서요.

2023-06-25 11:44 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +      DispatchQueue.main.async { viewStore.send(.offCurrentButtonTapped) }
ex)

```swift
        return .run { send in
          let accessToken = try await fetchKakaoOAuthToken()
          _ = try await loginClient.login(loginType: .kakao,
                                              accessToken: accessToken)
        } catch: { error, send in
          debugPrint(error)
        }
        .receive(on: DispatchQueue.main)
        .eraseToEffect()
```

2023-06-25 11:45 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +      DispatchQueue.main.async { viewStore.send(.offCurrentButtonTapped) }
코드작성해서 확인해보겠습니다~~

2023-06-25 11:51 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +      DispatchQueue.main.async { viewStore.send(.offCurrentButtonTapped) }
네 해결 안되면 일단 그대로 두고 다음에 고민해도 될것 같아요~

2023-06-25 11:55 UTC, Neph3779 reviewed
코멘트 하나 확인 부탁드려요~ @NewHooon

2023-06-25 11:55 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case offCurrentButtonTapped
그냥 currentButtonTapped라 쓰면 안되는걸까요?..
off라는 prefix가 잘 이해가 안가서 여쭤봅니당

2023-06-25 11:55 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    case offCurrentButtonTapped
제가 on/off로 관리하자 하던건 enum case로 on/off를 만들어보자는 이야기였어요

2023-06-25 12:05 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +      DispatchQueue.main.async { viewStore.send(.offCurrentButtonTapped) }
저 코드가 없으면 메인스레드에서 동작시키라는 보라돌이가 나오는거죠?

2023-06-25 14:52 UTC, NewHooon commented
@Neph3779 확인부탁드립니다~

2023-06-26 04:14 UTC, applebuddy commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
>      }
- executeRefreshMarker 라는 이름은 메서드명 같아보여서 recentExecutedRefreshState 라거나, enum에 어울리는 이름이 있지않을까 싶어요.

2023-06-26 04:59 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
>      }
넵.. 이번에 정말 많이배웁니다..!! 변수 네이밍의 중요성을 체감하네요.. 변수명 수정해보겠습니다 ㅎㅎ
꼼꼼한 pr리뷰 감사드립니다~

2023-06-26 05:01 UTC, Neph3779 submitted a review, later dismissed
고생하셨습니다~
조금 아쉬운 부분들은 우선 머지하고 
이후에 클러스터링 작업하며 리팩토링 논의해봐도 좋을 것 같아서 approve하겠습니다!

2023-06-26 05:01 UTC, Neph3779 commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var executeRefreshMarker: ExecuteState = .off
저도 state가 action 같아 보이는 느낌이 있네요...
currentPositionTransitionState 같은 state를 나타내는 변수명으로 변경하는게 좋아보여요

2023-06-26 05:03 UTC, NewHooon commented on Projects/Coffice/Sources/App/Dependencies/LocationManager.swift
> +  private var region = CLLocationCoordinate2D(latitude: 37.4971, longitude: 127.0287)
좋은 방식인 것 같습니다 해당 부분 확인했습니다!

2023-06-26 05:06 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +  }
네이밍 수정에 조금 더 신경쓰겠습니다~~!

어제 네이밍 작업을 하면서, 근본적으로 Store 리팩토링이 필요하다는 생각이 들었습니다..!

2023-06-26 05:06 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/CafeMapCore.swift
> +    var executeRefreshMarker: ExecuteState = .off
넵~ 추후 반영하겠습니다

2023-06-26 05:31 UTC, Neph3779 approved these changes
고생 많으셨습니다!

2023-06-26 05:32 UTC, merged

2023-06-26 05:54 UTC, NewHooon commented on Projects/Coffice/Sources/App/Main/Search/NaverMapView.swift
> +      DispatchQueue.main.async { viewStore.send(.offCurrentButtonTapped) }
넵 맞습니다~~